### ISSUE TITLE
Video in the header?

### ISSUE THREAD

**Issue by cmadland** [cogdog/wp-bigpicture#1]
Not so much an issue, but a question...

Can I use a video in the header of this theme?

**Comment by cogdog** [comment]
As it stands now there is no support for videos in the header image, but on reading the details it might not take much to do

https://make.wordpress.org/core/2016/11/26/video-headers-in-4-7/

The thing I’d need to sort out is how the theme layout will work since the first piece of content sits on a div that overlaps the header image

**Comment by cmadland** [comment]
Thanks Alan!
This is not at all a priority for me, so don't put too much effort in on my account!
cm
